-- CREATE DATABASE database_assignment;

SET TIME ZONE 'UTC';

CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  create_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    message TEXT NOT NULL,
    slot SMALLINT NOT NULL
);

CREATE USER app WITH PASSWORD 'mystrongPW26A!';

GRANT USAGE ON SCHEMA public TO app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;

GRANT ALL ON SCHEMA public TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;
GRANT USAGE, SELECT ON SEQUENCE messages_id_seq TO app;

SELECT * FROM messages;